# Generated by Django 2.0.4 on 2019-07-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('chassi', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('cor', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('ar_condicionado', models.BooleanField()),
                ('vidro_eletrico', models.BooleanField()),
                ('airbag', models.BooleanField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
