# Generated by Django 2.0.4 on 2019-07-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_auto_20190713_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.CharField(choices=[('FE', 'Ferrari'), ('LG', 'Lamborghini'), ('MC', 'Mercedes'), ('CH', 'Chevrolet'), ('TY', 'Toyota'), ('HY', 'Hyundai')], default='FE', max_length=2),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=20),
        ),
    ]
