# Generated by Django 2.0.4 on 2019-07-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_auto_20190713_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
