# Generated by Django 2.0.4 on 2019-07-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_auto_20190715_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(choices=[('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Mercedes', 'Mercedes'), ('Chevrolet', 'Chevrolet'), ('Toyota', 'Toyota'), ('Hyundai', 'Hyundai')], default='Hyundai', max_length=15),
        ),
    ]
