# Generated by Django 2.0.4 on 2019-07-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_auto_20190715_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='estado',
            field=models.CharField(choices=[('ZeroKm', 'ZeroKm'), ('Seminovo', 'Seminovo'), ('Usado', 'Usado')], default='ZeroKm', max_length=10),
        ),
    ]
