# Generated by Django 2.0.4 on 2019-07-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0007_auto_20190715_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
